name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
        kubernetes:
          - '1.17.13'
          - '1.18.10'
          - '1.19.3'
          - '1.20.1'
        laravel:
          - 7.*
          - 8.*
        prefer:
          - 'prefer-lowest'
          - 'prefer-stable'
        include:
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - K8s v${{ matrix.kubernetes }} --${{ matrix.prefer }}
    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, yaml
        coverage: pcov

    - uses: actions/cache@v1
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

    - uses: manusa/actions-setup-minikube@v2.2.0
      name: Setup Minikube
      with:
        minikube version: v1.16.0
        kubernetes version: "v${{ matrix.kubernetes }}"
        github token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Run Kubernetes Proxy
      run: |
        kubectl proxy --port=8080 &

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.prefer }} --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: |
        vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
